import Head from "next/head";
import {
  AiFillLinkedin,
  AiOutlineMail,
  AiOutlineMobile
} from "react-icons/ai";
import { useState } from "react";
import ch_dashboard from "../public/chazydes/ch_dashboard.png";
import ch_item_list from "../public/chazydes/ch_item_list.png";
import ch_item_details_page from "../public/chazydes/ch_item_details_page.png";
import ch_add_transaction from "../public/chazydes/ch_add_transaction.png";
import ch_transaction_details from "../public/chazydes/ch_transaction_details.png";
import ch_transactions_list from "../public/chazydes/ch_transactions_list.png";
import Image from "next/image";
import { Carousel } from 'react-responsive-carousel';
import "react-responsive-carousel/lib/styles/carousel.min.css";
import Link from "next/link";
import dynamic from 'next/dynamic'
const ReactPlayer = dynamic(() => import("react-player"), { ssr: false });

export default function Projects() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ralph Waldo Candaza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl">
                <Link
                    href="/"
                >
                  Ralph Waldo Candaza
                </Link>
            </h1>
            <ul className="flex items-center">
              <li>
                <Link
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="/projects"
                >
                  Sample Projects
                </Link>
              </li>
            </ul>
          </nav>
          <Carousel showArrows="true">
            <div class="screenshot-section sc1 shadow-lg p-10 rounded-xl dark:bg-white">
              <div>
                <h2 className="profile-banner-big-name text-center font-medium dark:text-teal-600">
                  Chazydes
                </h2>
                <h3 className="text-2xl text-center py-2 md:text-3xl mb-2">
                Item Inventory System
                </h3>
                <div style={{display: 'flex'}}>
                  <div class='vue-section'>
                    <div class="screenshot-img">
                      <Image src={ch_dashboard}/>
                    </div>
                    <h4 className="screenshot-label text-center dark:text-teal-600">
                      Dashboard
                    </h4>
                  </div>
                </div>
              </div>
            </div>
            <div class="screenshot-section sc2 shadow-lg p-10 rounded-xl dark:bg-white">
              <div>
                <h2 className="profile-banner-big-name text-center font-medium dark:text-teal-600">
                  Chazydes
                </h2>
                <h3 className="text-2xl text-center py-2 md:text-3xl mb-2">
                Item Inventory System
                </h3>
                <div style={{display: 'flex'}}>
                  <div class='vue-section'>
                    <div class="screenshot-img">
                      <Image src={ch_item_list}/>
                    </div>
                    <h4 className="screenshot-label text-center dark:text-teal-600">
                      Item List
                    </h4>
                  </div>
                </div>
              </div>
            </div>
            <div class="screenshot-section sc3 shadow-lg p-10 rounded-xl dark:bg-white">
              <div>
                <h2 className="profile-banner-big-name text-center font-medium dark:text-teal-600">
                  Chazydes
                </h2>
                <h3 className="text-2xl text-center py-2 md:text-3xl mb-2">
                Item Inventory System
                </h3>
                <div style={{display: 'flex'}}>
                  <div class='vue-section'>
                    <div class="screenshot-img">
                      <Image src={ch_item_details_page}/>
                    </div>
                    <h4 className="screenshot-label text-center dark:text-teal-600">
                      Item Details Page
                    </h4>
                  </div>
                </div>
              </div>
            </div>
            <div class="screenshot-section sc4 shadow-lg p-10 rounded-xl dark:bg-white">
              <div>
                <h2 className="profile-banner-big-name text-center font-medium dark:text-teal-600">
                  Chazydes
                </h2>
                <h3 className="text-2xl text-center py-2 md:text-3xl mb-2">
                Item Inventory System
                </h3>
                <div style={{display: 'flex'}}>
                  <div class='vue-section'>
                    <div class="screenshot-img">
                      <Image src={ch_add_transaction}/>
                    </div>
                    <h4 className="screenshot-label text-center dark:text-teal-600">
                      Add Transaction
                    </h4>
                  </div>
                </div>
              </div>
            </div>
            <div class="screenshot-section sc5 shadow-lg p-10 rounded-xl dark:bg-white">
              <div>
                <h2 className="profile-banner-big-name text-center font-medium dark:text-teal-600">
                  Chazydes
                </h2>
                <h3 className="text-2xl text-center py-2 md:text-3xl mb-2">
                Item Inventory System
                </h3>
                <div style={{display: 'flex'}}>
                  <div class='vue-section'>
                    <div class="screenshot-img">
                      <Image src={ch_transaction_details}/>
                    </div>
                    <h4 className="screenshot-label text-center dark:text-teal-600">
                      Transaction Details
                    </h4>
                  </div>
                </div>
              </div>
            </div>
            <div class="screenshot-section sc6 shadow-lg p-10 rounded-xl dark:bg-white">
              <div>
                <h2 className="profile-banner-big-name text-center font-medium dark:text-teal-600">
                  Chazydes
                </h2>
                <h3 className="text-2xl text-center py-2 md:text-3xl mb-2">
                Item Inventory System
                </h3>
                <div style={{display: 'flex'}}>
                  <div class='vue-section'>
                    <div class="screenshot-img">
                      <Image src={ch_transactions_list}/>
                    </div>
                    <h4 className="screenshot-label text-center dark:text-teal-600">
                      Transactions List
                    </h4>
                  </div>
                </div>
              </div>
            </div>
            <div class="screenshot-section sc7 shadow-lg p-10 rounded-xl dark:bg-white">
              <div>
                <h2 className="profile-banner-big-name text-center font-medium dark:text-teal-600">
                  Chazydes
                </h2>
                <h3 className="text-2xl text-center py-2 md:text-3xl mb-2">
                Item Inventory System
                </h3>
                <div style={{display: 'flex'}}>
                  <div class='vue-section'>
                    <div class="screenshot-img">
                    <ReactPlayer
                        className='react-player fixed-bottom'
                        url='videos/add-chopsticks-item.mp4'
                        controls={true}
                        width='100%'
                        height='100%'
                    />
                    </div>
                    <h4 className="screenshot-label text-center dark:text-teal-600">
                      Add Item Demo
                    </h4>
                  </div>
                </div>
              </div>
            </div>
            <div class="screenshot-section sc8 shadow-lg p-10 rounded-xl dark:bg-white">
              <div>
                <h2 className="profile-banner-big-name text-center font-medium dark:text-teal-600">
                  Chazydes
                </h2>
                <h3 className="text-2xl text-center py-2 md:text-3xl mb-2">
                Item Inventory System
                </h3>
                <div style={{display: 'flex'}}>
                  <div class='vue-section'>
                    <div class="screenshot-img">
                    <ReactPlayer
                        className='react-player fixed-bottom'
                        url='videos/items-out-of-stock.mp4'
                        controls={true}
                        width='100%'
                        height='100%'
                    />
                    </div>
                    <h4 className="screenshot-label text-center dark:text-teal-600">
                      Check Quantity of Items Demo
                    </h4>
                  </div>
                </div>
              </div>
            </div>
            <div class="screenshot-section sc9 shadow-lg p-10 rounded-xl dark:bg-white">
              <div>
                <h2 className="profile-banner-big-name text-center font-medium dark:text-teal-600">
                  Chazydes
                </h2>
                <h3 className="text-2xl text-center py-2 md:text-3xl mb-2">
                Item Inventory System
                </h3>
                <div style={{display: 'flex'}}>
                  <div class='vue-section'>
                    <div class="screenshot-img">
                    <ReactPlayer
                        className='react-player fixed-bottom'
                        url='videos/add-transaction.mp4'
                        controls={true}
                        width='100%'
                        height='100%'
                    />
                    </div>
                    <h4 className="screenshot-label text-center dark:text-teal-600">
                      Add Transaction Demo
                    </h4>
                  </div>
                </div>
              </div>
            </div>
          </Carousel>
        </section>
      </main>
    </div>
  );
}
